# Generated by Django 4.2.7 on 2023-12-20 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_cosmetic_clinical_trial_alter_cosmetic_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='clinical_trial',
            field=models.IntegerField(blank=True, choices=[(0, 'Одобрено'), (1, 'Отказано')], null=True, verbose_name='Результат клинических испытаний'),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 7, 45, 28, 333365, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
