# Generated by Django 4.2.7 on 2023-12-20 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_cosmetic_clinical_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 8, 3, 24, 521790, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
