# Generated by Django 4.2.5 on 2024-01-09 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 12, 54, 11, 390513, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subcosm',
            name='percent_in',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процентное содержание'),
        ),
    ]
